services:
  - type: web
    name: vidsrc-streaming-site
    env: node
    plan: free
    rootDir: .
    buildCommand: npm ci && npm run build && ls -la dist/
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    branch: main