services:
  - type: web
    name: vidsrc-streaming-site
    # Force redeploy - clear cache v2
    env: node
    plan: free
    rootDir: .
    buildCommand: npm ci --cache /tmp/empty-cache && npm run build && pwd && ls -la && ls -la dist/ && find . -name "index.html" -type f && find . -name "server.js" -type f && echo "=== Checking if dist/index.html exists ===" && ls -la dist/index.html || echo "dist/index.html NOT FOUND"
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    branch: main